require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Layout/DotPosition:
  Enabled: false